name: Build and Deploy

on:
  push:
    branches: [ master ]

jobs:
  build-storybook:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name:  Install deps
        run: npm install

      - name: Build
        run: npm run build-storybook

      - name: Upload build result
        uses: actions/upload-artifact@v1
        with:
          name: storybook-static
          path: ./storybook-static

  deploy-storybook:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: storybook-static

      - name: Transfer build files to server
        uses: appleboy/scp-action@v0.0.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "storybook-static/*"
          target: "/var/www/moviegate-storybook"
          strip_components: 1
